[package]
name = "vmm"
version = "0.1.0"
authors = ["rust-vmm AWS maintainers <rust-vmm-maintainers@amazon.com>"]
edition = "2018"

[dependencies]
event-manager = "0.4.0"
kvm-ioctls = { git = "https://github.com/rust-vmm/kvm.git"}
kvm-bindings = { git = "https://github.com/rust-vmm/kvm.git", features = ["fam-wrappers"] }
libc = "0.2.91"
linux-loader = { version = "0.13.0", features = ["bzimage", "elf"] }
vm-allocator = "0.1.0"
vm-memory = { version = "0.16.0", features = ["backend-mmap"] }
vm-superio = "0.8.0"
vmm-sys-util = "0.12.1"
vm-device = "0.1.0"

devices = { path = "../devices" }
vm-vcpu = { path = "../vm-vcpu" }
vm-vcpu-ref = { path = "../vm-vcpu-ref" }
utils = { path = "../utils" }
arch = { path = "../arch" }
